package main

func main() {
	// HelloWorld()
	// Values()
	// Variables()
	// Constants()
	// For()
	// IfElse()
	// Switch()
	// Arrays()
	// Slices()
	// Maps()
	// Functions()
	// MultipleReturnValues()
	// VariadicFunctions()
	// Closures()
	// Recursion()
	// RangeOverBuiltInTypes()
	// Pointers()
	// StringsAndRunes()
	// Structs()
	// Methods()
	// Interfaces()
	// Enums()
	// StructEmbedding()
	// Generics()
	// RangeOverIterators()
	// Errors()
	// CustomErrors()
	// Goroutines()
	// Channels()
	// ChannelBuffering()
	// ChannelSynchronization()
	// ChannelDirections()
	// Select()
	// Timeouts()
	// NonBlockingChannelOperations()
	// ClosingChannels()
	RangeOverChannels()
}
